run_name: drc_2019
path_to_fastq: /Volumes/aine_store/ukraine/fastq
path_to_fast5: /Volumes/aine_store/ukraine/fast5
reference_file: primer-schemes/EBOV/V3/EBOV.reference.fasta
primer_scheme_dir: primer-schemes
primer_scheme_version: EBOV/V3
min_length: 1000
max_length: 3000
barcodes:
    barcodeX: barcodeX
    # barcode01: barcode01
    # barcode02: barcode02
    # barcode03: barcode03
    # barcode04: barcode04
    # barcode05: barcode05
    # barcode06: barcode06
    # barcode07: barcode07
    # barcode08: barcode08
    # barcode09: barcode09
    # barcode10: barcode10
    # barcode11: barcode11
    # barcode12: barcode12
    # barcode13: barcode13
    # barcode14: barcode14
    # barcode15: barcode15
    # barcode16: barcode16
    # barcode17: barcode17
    # barcode18: barcode18
    # barcode19: barcode19
    # barcode20: barcode20
    # barcode21: barcode21
    # barcode22: barcode22
    # barcode23: barcode23
    # barcode24: barcode24
